#ifndef GLOBAL_H
#define GLOBAL_H

#define NODE_ID (1)
#define MONITORED_ITEM_ID (1)
#define MAX_NODES (6)

#define MONITORED_ITEM_IP ("FF80::F8E3:4E62:71BA:600A")

#define SIGNAL_STRENGTH_MONITOR (-35)
#define SIGNAL_STRENGTH_MONITORED_ITEM (-21)
#define SIGNAL_STRENGTH_NODE (-21)

#define NETIF_CHANNEL (11)

#define STARTUP_SLEEPTIME_SEC (1)

#define HAF_DEBUG
#define HAF_DEBUG_NODE_MAP
#define HAF_DEBUG_DISPATCH
#define HAF_DEBUG_DONT_PRINT_EMPTY_MAP

#define TEST_PRESENTATION

#endif /* GLOBAL_H */
